"""
API contract tests.

These tests pin the Django API schema (generated by drf-spectacular) against the
endpoints and response shapes the React frontend actually calls (`api.ts`) and
consumes (`types.ts`). If any endpoint or field changes on either side, the
contract breaks and these tests fail — no manual integration testing required.

Run slice:
    backend/env/bin/pytest core/tests/test_api_contract.py -q
"""

import pytest

from drf_spectacular.generators import SchemaGenerator


# (path, method) pairs consumed by frontend/src/services/api/**/*.ts
EXPECTED_ENDPOINTS = {
    "/auth/login/": ["post"],
    "/auth/logout/": ["post"],
    "/auth/registration/": ["post"],
    "/auth/registration/resend-email/": ["post"],
    "/auth/registration/verify-email/": ["post"],
    "/auth/password/change/": ["post"],
    "/auth/password/reset/": ["post"],
    "/auth/password/reset/confirm/": ["post"],
    "/auth/user/": ["get", "patch"],
    "/companies/companies/": ["get", "post"],
    "/companies/companies/{company_id}/": ["get", "patch"],
    "/companies/companies/{company_id}/jobs/": ["get"],
    "/jobs/get-jobs-list/": ["get"],
    "/jobs/get-job-details/{job_id}/": ["get"],
    "/jobs/get-owner-jobs-list/": ["get"],
    "/jobs/post-job/": ["post"],
    "/jobs/edit-job-post/{id}/": ["patch"],
    "/jobs/delete-job-post/{id}/": ["delete"],
    "/jobs/get_jobs_by_agent/": ["post"],
    "/jobs/get_resume_analysis/{job_id}/": ["post"],
    "/jobs/task-status/{task_id}/": ["get"],
    "/applications/apply-to-job/{job_id}/": ["post"],
    "/applications/get-application/{application_id}/": ["get"],
    "/applications/get-job-applications/{job_id}/": ["get"],
    "/applications/get-user-applications/": ["get"],
    "/applications/respond-to-application/{application_id}/": ["patch"],
}


# (path, method) -> required response fields, mirroring frontend/src/types.ts
EXPECTED_RESPONSE_FIELDS = {
    ("/auth/login/", "post"): {"access", "refresh"},
    ("/auth/logout/", "post"): {"detail"},
    ("/auth/registration/", "post"): {"detail"},
    ("/auth/registration/resend-email/", "post"): {"detail"},
    ("/auth/registration/verify-email/", "post"): {"detail"},
    ("/auth/password/change/", "post"): {"detail"},
    ("/auth/password/reset/", "post"): {"detail"},
    ("/auth/password/reset/confirm/", "post"): {"detail"},
    ("/auth/user/", "get"): {"id", "username", "email", "role"},
    ("/auth/user/", "patch"): {"id", "username", "email", "role"},
    ("/companies/companies/", "get"): {"id", "name", "followers_count"},
    ("/companies/companies/", "post"): {"id", "name", "followers_count"},
    ("/companies/companies/{company_id}/", "get"): {"id", "name", "followers_count"},
    ("/companies/companies/{company_id}/", "patch"): {"id", "name", "followers_count"},
    ("/companies/companies/{company_id}/jobs/", "get"): {"id", "title", "posted_at"},
    ("/jobs/get-jobs-list/", "get"): {"id", "title", "posted_at"},
    ("/jobs/get-job-details/{job_id}/", "get"): {"id", "title", "posted_at"},
    ("/jobs/get-owner-jobs-list/", "get"): {"id", "title", "posted_at"},
    ("/jobs/post-job/", "post"): {"title"},
    ("/jobs/edit-job-post/{id}/", "patch"): {"id", "title", "posted_at"},
    ("/jobs/get_jobs_by_agent/", "post"): {"task_id"},
    ("/jobs/get_resume_analysis/{job_id}/", "post"): {"task_id"},
    ("/jobs/task-status/{task_id}/", "get"): {"task_id", "status", "result"},
    ("/applications/apply-to-job/{job_id}/", "post"): {"resume"},
    ("/applications/get-application/{application_id}/", "get"): {
        "id",
        "status",
        "created_at",
        "updated_at",
        "applicant_id",
        "job_id",
        "resume",
    },
    ("/applications/get-job-applications/{job_id}/", "get"): {
        "id",
        "status",
        "created_at",
        "updated_at",
        "job_id",
    },
    ("/applications/get-user-applications/", "get"): {
        "id",
        "status",
        "created_at",
        "updated_at",
        "job_id",
    },
    ("/applications/respond-to-application/{application_id}/", "patch"): {
        "application_status",
    },
}


@pytest.fixture(scope="module")
def api_schema():
    generator = SchemaGenerator()
    # `public=True` mirrors SpectacularAPIView (SERVE_PUBLIC): without it, views
    # whose permissions reject the anonymous mock request (e.g. IsAuthenticated)
    # are silently dropped from the schema by drf-spectacular.
    return generator.get_schema(public=True)


def _normalize(path):
    """The schema renders URL kwargs as `{pk}` while the frontend uses `{id}`."""
    return path.replace("{pk}", "{id}")


def _get_operation(schema, path, method):
    for candidate in (path, _normalize(path)):
        operation = schema.get("paths", {}).get(candidate, {}).get(method.lower())
        if operation:
            return operation
    return None


def _resolve_ref(schema, ref):
    name = ref.split("/")[-1]
    return schema["components"]["schemas"][name]


def _get_success_response_properties(schema, path, method):
    operation = _get_operation(schema, path, method)
    assert operation is not None, f"{method.upper()} {path} missing in API schema"

    responses = operation.get("responses", {})
    status_code = next(
        (code for code in ("200", "201", "202") if code in responses), None
    )
    assert status_code is not None, (
        f"{method.upper()} {path} has no 2xx response: {sorted(responses)}"
    )

    response = responses[status_code]
    if "$ref" in response:
        response = _resolve_ref(schema, response["$ref"])

    content = response.get("content", {}).get("application/json", {})
    response_schema = content.get("schema", {})
    if "$ref" in response_schema:
        response_schema = _resolve_ref(schema, response_schema["$ref"])

    # Paginated responses wrap the items under `results` (DRF pagination).
    if response_schema.get("type") == "object" and "results" in response_schema.get("properties", {}):
        response_schema = response_schema["properties"]["results"]
        if "$ref" in response_schema:
            response_schema = _resolve_ref(schema, response_schema["$ref"])
        items = response_schema.get("items", {})
        if "$ref" in items:
            items = _resolve_ref(schema, items["$ref"])
        response_schema = items

    if response_schema.get("type") == "array":
        items = response_schema.get("items", {})
        if "$ref" in items:
            items = _resolve_ref(schema, items["$ref"])
        response_schema = items

    return set(response_schema.get("properties", {}).keys())


ENDPOINT_CASES = [
    (path, method)
    for path, methods in sorted(EXPECTED_ENDPOINTS.items())
    for method in methods
]


@pytest.mark.parametrize("path,method", ENDPOINT_CASES)
def test_endpoint_method_exists(api_schema, path, method):
    assert _get_operation(api_schema, path, method) is not None, (
        f"{method.upper()} {path} missing in API schema"
    )


@pytest.mark.parametrize("path,method", sorted(EXPECTED_RESPONSE_FIELDS))
def test_response_fields_present(api_schema, path, method):
    expected = EXPECTED_RESPONSE_FIELDS[(path, method)]
    properties = _get_success_response_properties(api_schema, path, method)
    missing = expected - properties
    assert not missing, (
        f"{method.upper()} {path} is missing response fields: {sorted(missing)}"
    )