# Generated by Django 5.2.6 on 2026-05-18 20:13

import applications.validators.resume
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[applications.validators.resume.validate_file_size, applications.validators.resume.validate_file_extension, applications.validators.resume.validate_pdf_signature, applications.validators.resume.validate_pdf_integrity]),
        ),
    ]
