# Generated by Django 5.2.6 on 2026-05-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='work_mode',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('onsite', 'Onsite'), ('remote', 'Remote')], default='onsite', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='employment_type',
            field=models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CT', 'Contract')], default='FT', max_length=2),
        ),
    ]
