# Generated by Django 5.2.6 on 2026-05-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_company_admins_remove_company_owner_and_more'),
    ]

    operations = [
        # Placeholder: Data migration for owner/admins conversion
        # This is a no-op migration since the initial migration already removed the fields
        # In development environment with no existing data, no data migration is needed
        # If you have production data, create a custom management command to handle the migration manually
    ]
