# Generated by Django 5.2.6 on 2026-05-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CANDIDATE', 'Candidate'), ('RECRUITER', 'Recruiter / Company'), ('ADMIN', 'System admin')], default='CANDIDATE', max_length=20),
        ),
    ]
